In [39]:
import numpy as np

array0 = np.array([[5, 2], [3, 4]])
# det0 = np.linalg.det(array0)

#Solutions for a simultaneous equations
array0 = np.array([[2, 3, -1], [3,1,2], [1,2,-5]])
array1 = np.array([[3,-1,-4], [1,2,-13], [2,-5, 11]])
det0 = np.linalg.det(array0) # Determinant of the coefficient matrix
det1 = np.linalg.det(array1)
print(det1/det0) # Value of x in the equations

#Consistency check. The det must be 0 to be consistent
array2 = np.array([[2,1,-5], [1,4,1], [3,-1,-10]])
det2 = np.linalg.det(array2)
# print(det2)

array3 = np.array([[4,2,3], [5,7,6]])
array4 = np.array([[1,8,9], [3,5,4]])
print(array3 + array4)

print(array3 - array4)
print("---------------------------")
print(array3 * 2)

#Multiplication and Division
array5 = np.array([[2,3,5,1], [4,6,0,7]])
array6 = np.array([[3],[4],[2],[9]])
print(array5 @ array6)  # Matrix multiplication
print("---------------------------")

array7 = np.array([[1,5], [2,7], [3,4]])
array8 = np.array([[8,4,3,1], [2,5,8,6]])
print(array7 @ array8)  # Matrix multiplication

print(np.linalg.matrix_transpose(array8))  # Transpose of a matrix

print(np.eye(3))  # Identity matrix of size 3x3

#Special Matrices
print(np.zeros((2,3)))  # 2x3 matrix of zeros
print(np.ones((3,2)))   # 3x2 matrix of ones
print(np.full((2,2), 7))  # 2x2 matrix filled with 7s
print(np.random.rand(2,2))  # 2x2 matrix with random values

#Inverse of a matrix
array9 = np.array([[2,3,5],[4,1,6], [1,4,0]])
transpose = array9.T #Another way to get transpose
print("Transpose of the matrix is:", transpose)
inverse = np.linalg.inv(array9)#*45
print("Inverse of the matrix is:", inverse)
print("Verification (Identity Matrix):", np.dot(array9, inverse))

#Solution of a set of linear equations. Ax = B
a = np.array([[1,2,1], [3,-4,-2], [5,3,5]])
invA = np.linalg.inv(a)
print("Inverse of A is:", invA)
b = np.array([[4], [2], [-1]])
solution = np.dot(invA, b)
print("Solution of the equations is:", solution)
solution = np.linalg.solve(a, b)
print("Solution of the equations is:", solution)


# Eigenvalues and Eigenvectors
matrix = np.array([[4, -1], [2, 1]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)
matrix = np.array([[2,3,-2], [1,4,-2], [2,10,-5]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)
matrix = np.array([[1,-1,0], [1,2,1], [-2,1,-1]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)

matrix = np.array([[4, 1], [3,2]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", np.round(eigenvectors,1))

matrix = np.array([[2,0, 1], [-1,4,-1], [-1,2,0]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", np.round(eigenvectors,1))

-1.9999999999999982
[[ 5 10 12]
 [ 8 12 10]]
[[ 3 -6 -6]
 [ 2  2  2]]
---------------------------
[[ 8  4  6]
 [10 14 12]]
[[37]
 [99]]
---------------------------
[[18 29 43 31]
 [30 43 62 44]
 [32 32 41 27]]
[[8 2]
 [4 5]
 [3 8]
 [1 6]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]
[[0.18979596 0.22906496]
 [0.60005873 0.76263277]]
Transpose of the matrix is: [[2 4 1]
 [3 1 4]
 [5 6 0]]
Inverse of the matrix is: [[-0.53333333  0.44444444  0.28888889]
 [ 0.13333333 -0.11111111  0.17777778]
 [ 0.33333333 -0.11111111 -0.22222222]]
Verification (Identity Matrix): [[ 1.00000000e+00 -1.38777878e-17  1.11022302e-16]
 [-1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Inverse of A is: [[ 4.00000000e-01  2.00000000e-01 -4.44089210e-17]
 [ 7.14285714e-01 -1.91417763e-17 -1.42857143e-01]
 [-8.28571429e-01 -2.00000000e-01  2.85714286e-01]]
Solution of the equations is: [[ 2.]
 [ 3.]
 [-4